name: Deploy-Network
on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
jobs:
  
  review:
    name: Review ChangeSet
    if: contains( github.base_ref, 'develop') || contains( github.base_ref, 'main')
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CFM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CFM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        ENVIRONMENT=`echo $REPO | tr "/" "-"`
        echo "Environment name: $ENVIRONMENT"
        echo "::set-output name=environment::$ENVIRONMENT"
    - name: cloudformation changeset review
      id: service-review
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: "deploy-netwrok-test"
        template: ./netwroking/networking.yaml
        no-fail-on-empty-changeset: "1"
        no-execute-changeset: "1"
        parameter-overrides: >-
          EnvironmentName=poc-test,
          VpcCIDR=10.0.0.0/16,
          PublicSubnet1CIDR=10.0.1.0/24,
          PublicSubnet2CIDR=10.0.2.0/24,
          PrivateSubnet1CIDR=10.0.3.0/24,
          PrivateSubnet2CIDR=10.0.4.0/24
  deploy_network:
    name: Deploy network-stack
    if: contains( github.ref, 'develop') || contains( github.ref, 'main')
    #needs: [html-publish, artifactory_deployment]
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CFM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CFM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Configure environment name
      id: env-name
      env:
        REPO: ${{ github.repository }}
      run: |
        ENVIRONMENT=`echo $REPO | tr "/" "-"`
        echo "Environment name: $ENVIRONMENT"
        echo "::set-output name=environment::$ENVIRONMENT"
        sleep $[ ( $RANDOM % 10 )  + 1 ]s
    
    - name: Service network
      id: service-network
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: "service-network-deploy"
        template: ./networking/networking.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          EnvironmentName=poc-test,
          VpcCIDR=10.0.0.0/16,
          PublicSubnet1CIDR=10.0.1.0/24,
          PublicSubnet2CIDR=10.0.2.0/24,
          PrivateSubnet1CIDR=10.0.3.0/24,
          PrivateSubnet2CIDR=10.0.4.0/24